#let zds-number = "0002"
#let zds-title = "zenfmt: Architecture and Implementation"
#let zds-state = "discussion"
#let zds-created = "2026-08-06"
#let zds-discussion = "Architecture and first-release plan for the zenfmt document converter"
#let zds-labels = ("architecture", "ast", "filters", "plugins", "formats",)
#let zds-authors = ("Zen Contributors <team@insan.ai>",)
#let zds-category = "Architectural Specification"
#let zds-status = "Open for Discussion"
#let zds-last-updated = "2026-08-06"

#import "../../shared/zds.typ": zds-document
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

#let c-in = (fill: rgb("dbeafe"), stroke: rgb("1d4ed8"))
#let c-ir = (fill: rgb("ede9fe"), stroke: rgb("7c3aed"))
#let c-out = (fill: rgb("dcfce7"), stroke: rgb("15803d"))
#let c-aux = (fill: rgb("fef3c7"), stroke: rgb("b45309"))
#let c-mute = (fill: rgb("f1f5f9"), stroke: rgb("64748b"))

#let box-node(pos, name, caption, palette, width: auto) = node(
  pos,
  align(center)[
    #text(9.5pt, weight: "bold", fill: palette.stroke.darken(20%))[#name]
    #if caption != none [
      #linebreak()
      #text(7pt, fill: rgb("475569"))[#caption]
    ]
  ],
  fill: palette.fill,
  stroke: 0.9pt + palette.stroke,
  shape: fletcher.shapes.rect,
  corner-radius: 5pt,
  inset: 7pt,
  width: width,
)

#let edge-label(body) = text(7.3pt, fill: rgb("475569"), style: "italic")[#body]

// PDF renders diagrams directly; the experimental HTML export embeds them as
// typeset frames so the figures survive on the bundle website.
#let zds-figure(body) = context {
  if target() == "html" {
    html.frame(align(center, body))
  } else {
    align(center, body)
  }
}

#let tbl(..args) = table(
  stroke: 0.5pt + rgb("d7dee8"),
  inset: 6pt,
  ..args,
)

#show: doc => zds-document(
  zds-number,
  zds-title,
  doc,
  authors: zds-authors,
  state: zds-state,
  created: zds-created,
  discussion: zds-discussion,
  labels: zds-labels,
  category: zds-category,
  status: zds-status,
  last-updated: zds-last-updated,
)

= Abstract

zenfmt is a document converter in the shape of pandoc: it parses a document
into an abstract syntax tree, optionally transforms that tree, and serializes
it in another format. This record specifies the whole system.

Three commitments shape the design.

*The representation is a real AST*, structurally compatible with pandoc's
document model: blocks nest, inlines nest, and every node carries the
identifier, classes, and key-value attributes that make a tree addressable. It
is *stored* as a flat preorder struct-of-arrays in one arena — the technique
Zig's own compiler uses for its syntax tree — which builds the AST out of `u32`
indices rather than pointers, and turns several tree operations into linear
scans and `memcpy`.

*Filters are first-class and written in Zig*, in the manner of `build.zig`: a
filter is a Zig type with `visitBlock` and `visitInline` methods, registered
into a pipeline by a `pub fn filters(p: *Pipeline) void` entry point that a
user writes in their own project and compiles against the zenfmt module. There
is no embedded scripting language and no serialization boundary. Because a
transform rebuilds rather than mutates, and because an unchanged subtree is a
contiguous slice, a filter that touches nothing costs one `memcpy` per array.

*The engine knows no formats.* Readers, writers, and filters are plugins
resolved through a comptime registry, and the conversion matrix is generated by
the compiler. Adding a format is one flat file and one table row.

The first release reads the office formats and writes Markdown, with the
lightweight markup formats — AsciiDoc, reStructuredText, and the rest —
following as plugins against an unchanged core. This record defines the AST,
the traversal and rewriting algorithms, the filter contract, the plugin
contract, the registry and static router, the memory model, the Elm-style
diagnostic reports, OOXML ingestion and its security limits, the Markdown
writer's output rules, the coding standard, the CLI, the test strategy, and the
phased plan.

= Introduction

A document converter is a compiler, and is best built like one: a front end per
input language, a shared tree in the middle, a back end per output language,
and a pass pipeline between them. The comparison predicts where the difficulty
lives. It is not in any single parser. It is in the tree, which every front end
must reach and every back end must serve, and which cannot be changed later
without touching everything.

pandoc has demonstrated the shape of the answer over fifteen years, and this
design follows it deliberately rather than inventing a rival. The
`Text.Pandoc.Definition` types — `Block`, `Inline`, `Attr`, and a document
carrying metadata — are a good factoring of what documents contain, proven
across forty formats. zenfmt adopts that shape.

What zenfmt changes is the *implementation* of the tree, not its structure.
Where pandoc has a recursive Haskell data type on a garbage-collected heap,
zenfmt has the same tree stored as flat arrays of fixed-size records in an
arena, with `u32` indices for edges. This is not a compromise of the AST; it is
a representation choice for it, and the same one Zig's compiler makes for its
own syntax tree in `std.zig.Ast`. It buys cache locality, allocation-free node
creation, and — the point that matters most for filters — the ability to copy
an untouched subtree with a single `memcpy`, because a subtree is a contiguous
range.

The second thing a converter accumulates is decisions that are invisible in the
code. When a reader emits nothing for a construct, nothing in the source
distinguishes "this does not survive the projection" from "we have not written
this yet". ZDS 0001 requires format records to carry an explicit omissions
section for exactly this reason, and this record establishes the pattern.

== Relationship to other records

ZDS 0001 defines the process and the format-record obligations. This record is
the architectural parent of every future format record: a plugin ZDS states its
mapping table, its omissions, and its round-trip expectations, and inherits
everything here about the AST, the contract, and the limits. A change to the
node set itself amends this record and requires its own.

= Terminology and Scope

- *AST*: the abstract syntax tree defined under _The Document AST_. Two node
  arrays, a text pool, and side tables, all in one arena.
- *node*: a `Block` or an `Inline`, identified by a `u32` index into its array.
- *reader*: a plugin that parses one input format into the AST. A front end.
- *writer*: a plugin that serializes the AST into one output format. A back end.
- *filter*: a transform from AST to AST, written in Zig, that a user composes
  into a pipeline.
- *plugin*: a reader, a writer, or a filter. One Zig file, one public type.
- *registry*: the comptime tables in `src/registry.zig` naming every plugin.
- *static router*: the engine's comptime-generated dispatch from a runtime
  format pair to a monomorphized pipeline.
- *report*: a user-facing diagnostic, rendered in the Elm style described under
  _Diagnostics and Error Messages_.
- *lossy*: a mapping that discards information present in the source. Every
  interesting mapping here is lossy in at least one direction.

In scope: the AST, the traversal and rewriting algorithms, the filter system,
the plugin contract, the engine, the registry, the memory model, diagnostics,
ingestion for the first-release formats, the Markdown writer, the coding
standard, the CLI, the build, and the test strategy.

Out of scope: templating and standalone-document wrapping, citation
processing, PDF output via a typesetter, and any writer other than Markdown in
the first release. Each is a candidate for a later record; none is precluded.

= Problem Statement

A converter has five hard parts, and only the first is a parsing problem.

*The tree must serve formats that disagree about structure.* DOCX has no list
element: a list is a run of paragraphs carrying numbering properties that point
into a shared numbering definition. HTML has an explicit list element and
permits arbitrary nesting inside items. AsciiDoc and reStructuredText have
block-level directives with no HTML analogue. CSV has no inline structure at
all. Markdown distinguishes tight and loose lists, a distinction DOCX cannot
express. A tree shaped like any one of these makes the others expensive.

*Transformation must be possible without forking the program.* The reason
pandoc is used rather than merely admired is that a user can write a filter.
Converting a manual usually needs one or two document-specific adjustments —
shift every heading down a level, rewrite internal links, drop a class of
admonition — and a converter that cannot express those is a converter people
work around. This requires a real tree with node identity, and an API for
walking and rewriting it.

*Fidelity is not achievable and must therefore be specified.* Every conversion
discards something; the question is whether the user is told. A converter that
silently drops the tracked-changes history, the comment threads, and the
embedded chart while emitting clean-looking Markdown has produced a plausible
lie.

*The input is untrusted by construction.* The program's entire purpose is to
open a file someone else produced. DOCX and ODT are ZIP archives supporting
unbounded expansion ratios; XML supports quadratic entity expansion; archive
entry names can contain `..`. Resource limits are a design surface, not an
implementation detail.

*Extension must not touch the core.* A converter's value is roughly the product
of its input and output counts, so the cost of adding a format sets the
project's ceiling. If adding DOCX means editing the engine, the engine
accumulates format knowledge until it cannot be reasoned about.

= Goals and Non-Goals

== Goals

+ *A real AST.* Blocks nest, inlines nest, nodes carry attributes, and any node
  can be inspected, replaced, unwrapped, or deleted by a transform. Structural
  compatibility with pandoc's document model, so experience and mental models
  transfer.
+ *Filters in Zig, in the `build.zig` manner.* A user writes a Zig file
  declaring a pipeline, compiles it against the zenfmt module, and gets a
  binary with their transforms in it. No embedded interpreter, no serialization
  boundary, no dynamic loading.
+ *Flat, data-oriented storage.* Struct-of-arrays, `u32` edges, one arena per
  conversion, no allocation per node, contiguous subtrees.
+ *Algorithmic efficiency that follows from the storage*, not from
  micro-optimization: `O(1)` subtree skip, vectorizable tag scans, `memcpy`
  subtree sharing during rewrites, and a single linear pass for the common
  traversal.
+ *A core with no format knowledge.* No identifier from any file specification
  appears in the engine or the AST. Adding a format touches one new file and
  one registry row.
+ *Explicit lossiness.* Every discarded construct is recorded in a report at
  runtime and in an omissions table in the plugin's ZDS.
+ *Error messages in the Elm tradition.* A diagnostic names what happened,
  shows the input that caused it, and says what to do — never a bare code.
+ *Bounded resource use on hostile input.* Every limit has a name, a default, a
  CLI override, and a reason recorded here.
+ *Deterministic output.* The same input bytes produce the same output bytes,
  on every platform and in every build mode.
+ *Maintainability as a stated constraint*, enforced by the coding standard:
  bounded everything, no recursion, files under 1,000 lines, `src/` flat.

== Non-Goals

- *Byte-level round-trip fidelity.* DOCX to Markdown and back will not
  reproduce the original. This follows from having one shared tree.
- *Matching pandoc's format count.* zenfmt aims at a well-understood set done
  thoroughly.
- *An embedded scripting language.* Filters are Zig. A JSON bridge to external
  filters is a possible later compatibility feature, not a goal.
- *Layout preservation.* Pagination, columns, absolute positioning, and
  typography are not represented.
- *Rendering.* No output format requires a typesetter or a font stack.

= Design Overview

A conversion is a pipeline with a tree in the middle and an arbitrary number of
transforms on it.

#zds-figure(
  diagram(
    spacing: (15mm, 11mm),
    node-outset: 2pt,
    edge-stroke: 0.85pt + rgb("64748b"),
    box-node((0, 0), [Input], [file, stdin], c-mute),
    box-node((1, 0), [Reader], [one per #linebreak() input format], c-in),
    box-node((2, 0), [AST], [nested blocks #linebreak() nested inlines], c-ir),
    box-node((3, 0), [Filters], [zero or more #linebreak() AST → AST], c-aux),
    box-node((4, 0), [Writer], [one per #linebreak() output format], c-out),
    box-node((5, 0), [Output], [file, stdout], c-mute),
    box-node((3, 1), [Reports], [Elm-style #linebreak() diagnostics], c-mute),
    edge((0, 0), (1, 0), "-|>"),
    edge((1, 0), (2, 0), edge-label[build], "-|>"),
    edge((2, 0), (3, 0), "-|>"),
    edge((3, 0), (3, 0), edge-label[rebuild], "-|>", bend: 130deg),
    edge((3, 0), (4, 0), edge-label[final tree], "-|>"),
    edge((4, 0), (5, 0), "-|>"),
    edge((1, 0), (3, 1), "--|>"),
    edge((3, 0), (3, 1), "--|>"),
    edge((4, 0), (3, 1), "--|>"),
  ),
)

The engine owns the arena, the report sink, and the limits. It hands the reader
a `Builder` and the input; it freezes the result into a `Document`; it runs the
filter pipeline, each stage producing a new `Document` in the same arena; it
hands the last one to the writer. It never inspects a node, never looks at a
tag, and never knows which plugins it called.

Two properties follow from the AST sitting between the halves. Each reader and
each writer is compiled once regardless of how many formats exist, so the
conversion matrix does not multiply code size — only the small dispatch glue is
quadratic. And a reader can be tested against the AST directly, with no writer
involved, which is what the tree-test suite does.

= The Document AST

== Shape: pandoc's model

The node set is deliberately close to `Text.Pandoc.Definition`. Where a
construct exists in pandoc it keeps pandoc's name and meaning, so a reader of
one system can read the other, and so a future pandoc-JSON bridge is a
translation rather than a redesign.

```zig
pub const BlockTag = enum(u8) {
    // Leaf blocks: content is inline.
    plain,             // a paragraph that must not be wrapped in <p>
    para,
    line_block,        // preserved line breaks, as in poetry
    heading,           // pandoc's Header
    code_block,        // content is raw text, not inlines
    raw_block,         // format-specific literal
    horizontal_rule,

    // Container blocks: content is blocks.
    block_quote,
    div,               // pandoc's Div: a generic attributed container
    figure,
    bullet_list,
    ordered_list,
    list_item,
    definition_list,
    definition_item,
    definition_term,   // content is inline
    definition_body,
    table,
    caption,
    table_head,
    table_body,
    table_foot,
    table_row,
    table_cell,
};

pub const InlineTag = enum(u8) {
    // Leaf inlines.
    str,               // a run of text containing no whitespace
    space,
    soft_break,
    line_break,
    code,              // inline code; content is raw text
    math,              // attr selects inline or display
    raw_inline,

    // Container inlines: content is inlines.
    emph,
    strong,
    strikeout,
    superscript,
    subscript,
    small_caps,
    underline,
    quoted,            // attr selects single or double
    link,
    image,             // children are the alt text
    span,              // pandoc's Span: a generic attributed container
    cite,

    // Container inline whose content is blocks.
    note,              // pandoc's Note: a footnote body
};
```

Three points about this list are decisions rather than transcription.

`space`, `soft_break`, and `line_break` are separate leaf nodes rather than
characters inside a text run, exactly as in pandoc. This costs nodes and buys
the ability for a filter to distinguish a line wrap in the source from a
deliberate break, and for a writer to re-wrap text without guessing.

`div` and `span` exist so a format's structure that has no direct node — an
AsciiDoc admonition, an HTML `section`, a DOCX content control, an RST
directive — survives as an attributed container rather than being flattened.
They are the extension point that keeps the node set closed, they are what most
filters match on, and they are in the set from the start rather than added when
the first such format arrives.

`emph` and `strong` are containers, not flags. This reverses an earlier draft;
the reasoning is under _Why the tree is a tree_.

== Storage: flat, preorder, struct-of-arrays

The tree is stored as two `std.MultiArrayList` arrays — one of blocks, one of
inlines — each holding its nodes in document preorder, each node recording the
index one past its last descendant.

```zig
pub const Range = struct {
    start: u32,
    len: u32,

    pub const empty: Range = .{ .start = 0, .len = 0 };

    pub fn end(r: Range) u32 {
        return r.start + r.len;
    }
};

pub const Block = struct {
    tag: BlockTag,
    /// Tag-specific payload. Never read directly; the encoding is defined
    /// once, in attr.zig, and reached through accessors.
    attr: u32,
    /// Index into `Document.attrs` for the (id, classes, pairs) triple, or
    /// `none` when the tag carries no attributes.
    attrs: u32,
    /// Inline children, for tags whose content is inline. Container blocks
    /// hold `Range.empty`.
    inlines: Range,
    /// One past this node's last descendant block. A leaf at index `i` has
    /// `subtree_end == i + 1`.
    subtree_end: u32,
};

pub const Inline = struct {
    tag: InlineTag,
    attr: u32,
    attrs: u32,
    /// Meaning depends on the tag: a text range for `str`, `code`, `math`,
    /// and `raw_inline`; a block range for `note`; empty otherwise.
    data: Range,
    /// One past this node's last descendant inline.
    subtree_end: u32,
};

pub const Document = struct {
    blocks: std.MultiArrayList(Block).Slice,
    inlines: std.MultiArrayList(Inline).Slice,
    /// The top-level block forest. Blocks outside this range are note bodies.
    body: Range,
    text: []const u8,
    attrs: []const Attr,
    strings: []const Range,
    links: []const Link,
    media: []const Media,
    meta: []const Meta,
};
```

Children of node `i` are found by hopping: start at `i + 1`, and from each
child `j` jump to `subtree_end[j]`, stopping at the parent's own
`subtree_end`. There is no child list to allocate and no parent pointer to
maintain.

```zig
pub const Children = struct {
    ends: []const u32,
    cursor: u32,
    bound: u32,

    pub fn init(doc: *const Document, parent: u32) Children {
        const ends = doc.blocks.items(.subtree_end);
        assert(parent < ends.len);
        return .{ .ends = ends, .cursor = parent + 1, .bound = ends[parent] };
    }

    pub fn next(it: *Children) ?u32 {
        assert(it.cursor <= it.bound);
        if (it.cursor == it.bound) return null;
        const index = it.cursor;
        it.cursor = it.ends[index];
        assert(it.cursor > index);
        return index;
    }
};
```

The three properties this layout is chosen for:

#tbl(
  columns: (auto, 1fr),
  table.header([*Property*], [*Consequence*]),
  [A subtree is a contiguous slice],
  [Copying an unchanged branch during a filter rebuild is one `memcpy` per
    array. This is the property the filter system is built on, and a
    pointer-based tree cannot have it.],

  [`subtree_end` skips a subtree in `O(1)`],
  [A filter that only cares about `link` nodes advances past whole untouched
    branches without visiting them.],

  [Struct-of-arrays puts every tag in one byte column],
  [`std.mem.indexOfScalar` over `blocks.items(.tag)` is a contiguous byte scan
    the compiler vectorizes. "Find every table in this document" is a
    `memchr`, not a tree walk.],
)

== Attributes

Every node that pandoc gives an `Attr` gets one here: an identifier, a class
list, and ordered key-value pairs.

```zig
pub const Attr = struct {
    id: Range,        // into text; empty when absent
    classes: Range,   // into strings, each a Range into text
    pairs: Range,     // into pairs, each two Ranges into text
};
```

Attributes carry heading identifiers, the `code_block` language as the first
class, `div` and `span` roles, and everything a format has that the node set
does not name. They are also how filters select: matching a class is the
idiomatic way to write a transform that applies to some nodes and not others.

`Block.attr` and `Inline.attr` remain a `u32` tag-specific payload for the
small enumerated things that would be wasteful as string attributes. The
encoding is defined once, in `attr.zig`, and reached only through accessors, so
the compiler checks the tag-to-payload relationship at every use. The
preliminary sketch called this field `extra` and left its meaning to
convention; that is how a field becomes folklore.

#tbl(
  columns: (auto, 1fr),
  table.header([*Tag*], [*`attr` encoding*]),
  [`heading`], [Level, 1 to 6.],
  [`ordered_list`],
  [Packed: bits 0..1 the number style (decimal, lower-alpha, upper-alpha,
    lower-roman, upper-roman), bits 2..3 the delimiter (period, paren,
    two-paren), bit 4 tight, bits 8..31 the start number.],
  [`bullet_list`], [Bit 0: tight.],
  [`code_block`], [Reserved; the language is the first class in `attrs`.],
  [`raw_block`, `raw_inline`], [The `Format` the content is literal for.],
  [`table_cell`], [Packed: bits 0..7 column span, bits 8..15 row span, bits 16..17 alignment.],
  [`table`], [Column count, set on close.],
  [`quoted`], [0 single, 1 double.],
  [`math`], [0 inline, 1 display.],
  [`link`, `image`], [Index into `Document.links` for target and title.],
  [`note`], [The note's ordinal.],
  [`str`, `code`, `emph`, `strong`, and the rest], [Zero. Checked by the validator.],
)

== The text pool and side tables

All text lives in one growable byte array; a `Range` into it is 8 bytes and
never dangles. Text is stored *decoded*: XML character references, RTF hex
escapes, and HTML entities are resolved by the reader, so no writer ever sees a
source format's escaping. Text is UTF-8, and readers of other encodings
transcode on the way in.

Repeated strings — class names, language tags, attribute keys — are interned
through a hash map that lives only during the build and is dropped when the
`Document` is frozen. Interning is what keeps the attribute machinery cheap: a
document with ten thousand `div` nodes carrying the same class stores that
class once.

```zig
pub const Link = struct {
    target: Range,
    title: Range,
};

pub const Media = struct {
    source: Range,   // path, URL, or archive entry name
    bytes: Range,    // extracted content; empty in the first release
    mime: Range,
};

pub const Meta = struct {
    key: Range,
    /// Metadata values are documents in miniature, so a value is a block
    /// range: a title with emphasis in it survives.
    value: Range,
};
```

== Invariants

The following hold for every `Document` handed to a filter or a writer. They
are checked by `ast.validate`, which runs on every conversion in `Debug` and
`ReleaseSafe`, after every filter stage, in every test, and on every fuzz
iteration. The validator is the oracle that makes reader and filter fuzzing
meaningful: a plugin that produces a structurally impossible tree fails even
when nothing crashes.

+ `subtree_end[i] > i` and `<= len`, in both arrays.
+ For any `j` in `(i, subtree_end[i])`, `subtree_end[j] <= subtree_end[i]`.
  Subtrees nest properly.
+ Every `Range` lies within the array it indexes.
+ Container tags hold `inlines == Range.empty`; leaf-content tags have
  `subtree_end == i + 1`.
+ Child tags appear only under their parent tag: `list_item` under a list,
  `table_row` under a table section, `table_cell` under `table_row`,
  `definition_term` and `definition_body` under `definition_item`.
+ A container inline has at least one child, except `image`, whose alt text may
  be empty.
+ `note.data` names a block range outside `body`, and every `note` ordinal is
  distinct.
+ Depth does not exceed `limits.max_depth` in either tree.
+ `attr` is zero for every tag whose row above says so.
+ The text pool is valid UTF-8, and no `str` node contains a whitespace
  character — whitespace is a `space`, `soft_break`, or `line_break` node.
+ No two adjacent siblings are both `str`; readers coalesce.

== A worked example

The Markdown fragment

```md
## The *quick* [brown](http://x) fox

- one
- two

  still two
```

produces the two trees below. Indentation shows the nesting that `subtree_end`
encodes; it is not stored.

#tbl(
  columns: (auto, 1fr, auto, auto, auto),
  align: (right, left, right, right, right),
  table.header([*i*], [*block*], [*attr*], [*subtree#linebreak()end*], [*inlines*]),
  [0], [`heading`], [2], [1], [0..9],
  [1], [`bullet_list`], [`tight`], [5], [—],
  [2], [`  list_item`], [0], [3], [—],
  [3], [`    plain`], [0], [4], [9..10],
  [4], [`  list_item`], [0], [7], [—],
  [5], [`    para`], [0], [6], [10..11],
  [6], [`    para`], [0], [7], [11..12],
)

Block 4's `subtree_end` is 7 while block 2's is 3: the second item holds two
paragraphs, the first holds one, and both are found by the same hop. Item one's
child is `plain` and item two's are `para` — the tight-versus-loose distinction
pandoc draws, which a writer needs in order to reproduce blank lines
faithfully.

#tbl(
  columns: (auto, 1fr, auto, auto),
  align: (right, left, left, right),
  table.header([*j*], [*inline*], [*data / attr*], [*subtree#linebreak()end*]),
  [0], [`str`], [`"The"`], [1],
  [1], [`space`], [—], [2],
  [2], [`emph`], [—], [4],
  [3], [`  str`], [`"quick"`], [4],
  [4], [`space`], [—], [5],
  [5], [`link`], [`links[0]`], [7],
  [6], [`  str`], [`"brown"`], [7],
  [7], [`space`], [—], [8],
  [8], [`str`], [`"fox"`], [9],
)

The heading's `inlines` range is 0..9. Its seven top-level children are the
ones reachable by hopping from 0, which skips the children of `emph` and `link`
without a test for what they are.

== Why the tree is a tree

An earlier draft of this record proposed a flat inline layer: a sequence of
text runs each carrying a style bitset, with no inline nesting. The argument
was that the office formats contain no inline nesting to preserve — DOCX runs
carry independent property flags, and so do ODT spans and RTF groups — so
building a tree from flags means inventing structure the source never
specified.

That argument is right about the readers and wrong about the system, for three
reasons.

*Filters need node identity.* A transform that wraps every `code` inline in a
`link` to an API reference has to put a node around another node. A bitset can
be set and cleared; it cannot be wrapped. Every interesting filter — unwrap
this container, wrap that one, replace a node with a subtree — is a structural
edit, and a flat run layer offers nothing to edit. Since filters are a first
requirement rather than a later addition, this alone settles it.

*Not every inline container is a style.* `link`, `image`, `note`, `span`, and
`cite` carry payloads and children that no flag set can express. Once the
representation must nest for those, making `emph` and `strong` different in
kind buys nothing and costs a special case in every walker.

*Compatibility with pandoc's model has value the flat form forfeits.* A
document model people already know is easier to write plugins against, easier
to explain, and leaves a JSON bridge to the existing filter ecosystem as a
tractable later option rather than a rewrite.

What the flat-run argument does establish is a requirement on readers, and it
is kept: *a reader converting a flag set to nesting must use a canonical
order*, so bold-italic text produces the same tree no matter which flag the
source listed first. The order is `link`, `strong`, `emph`, `strikeout`,
`superscript`, `subscript`, `small_caps`, `underline`, outermost first. It is
stated once, here, and asserted by a shared test that every flag-based reader
runs.

== The Builder

Readers and filters do not touch `Document`. They append through a `Builder`,
which owns the growable arrays, the interning table, and the open-node stack.

```zig
pub const Builder = struct {
    blocks: std.MultiArrayList(Block) = .empty,
    inlines: std.MultiArrayList(Inline) = .empty,
    text: std.ArrayList(u8) = .empty,
    attrs: std.ArrayList(Attr) = .empty,
    // ... side tables, the intern map, the open-node stack

    /// Opens a container block; must be matched by `closeBlock`.
    pub fn openBlock(b: *Builder, gpa: Allocator, tag: BlockTag, a: Attrs) !u32;
    pub fn closeBlock(b: *Builder, gpa: Allocator) void;
    pub fn leafBlock(b: *Builder, gpa: Allocator, tag: BlockTag, a: Attrs) !u32;

    /// Opens a container inline; must be matched by `closeInline`.
    pub fn openInline(b: *Builder, gpa: Allocator, tag: InlineTag, a: Attrs) !u32;
    pub fn closeInline(b: *Builder, gpa: Allocator) void;

    /// Appends text, splitting on whitespace into `str` and `space` nodes and
    /// coalescing with a preceding `str`, so a reader appending arbitrary
    /// chunks still produces a canonical tree.
    pub fn text(b: *Builder, gpa: Allocator, bytes: []const u8) !void;

    /// Copies a whole subtree from another document: the fast path behind
    /// filter subtree sharing. One `memcpy` per array plus an index rebase.
    pub fn copyBlocks(b: *Builder, gpa: Allocator, from: *const Document, root: u32) !u32;
    pub fn copyInlines(b: *Builder, gpa: Allocator, from: *const Document, root: u32) !u32;

    /// Freezes into a `Document`. Asserts the open stack is empty.
    pub fn finish(b: *Builder) Document;
};
```

`text` is the one place the `Builder` is opinionated, and deliberately: the
whitespace and coalescing invariants are easier to hold in one function than in
nine readers.

`finish` asserts the open stack is empty. A plugin that returns unbalanced is a
bug, not a recoverable condition, and it is caught in that plugin's own tests
rather than papered over by an auto-close.

= Traversal and Rewriting Algorithms

The storage was chosen for these. This section states what it buys and what
each operation costs.

== Bounded, non-recursive walking

No traversal in zenfmt recurses. Every walker keeps an explicit stack of open
node indices bounded by `limits.max_depth`, checked on push. This follows the
coding standard's prohibition on recursion, and it is a safety rule before it
is a style rule: nesting depth is attacker-controlled, and a bounded stack
turns a stack overflow into a report.

The common traversal does not need the stack at all. Emitting a document in
document order is a single forward scan over the array, because preorder
storage *is* document order. The stack is needed only for writers that must
emit something on the way out of a node, and those keep one entry per open
container.

== Skipping and scanning

Two operations a pointer-based tree cannot do cheaply:

*Subtree skip.* A walker that decides a node is uninteresting sets
`i = subtree_end[i]` and continues. The entire branch costs nothing — not one
cache line is touched.

*Tag scan.* Because storage is struct-of-arrays, `blocks.items(.tag)` is a
contiguous `[]BlockTag`, one byte per node. Finding every table in a document
is `std.mem.indexOfScalar` over that column: a vectorized byte scan at memory
bandwidth, with no pointer chasing and no node loads. Filters that match a
single tag are implemented this way, and the pipeline recognizes them — a
filter declaring `pub const matches: []const BlockTag = &.{.table}` gets the
scan path rather than the walk path.

== The rebuild transform, with subtree sharing

Filters do not mutate. A stage reads one `Document` and writes another into the
same arena. The naive cost of that is a full copy per stage, and the algorithm
that avoids it is why this record cares about storage layout.

The transform is a post-order pass returning, for each node, whether anything
beneath it changed:

+ Visit the node's children first, recording whether any child was rewritten.
+ Call the filter's `visitBlock` or `visitInline` for this node.
+ If the filter returned `keep` *and* no descendant changed, emit the node by
  copying its whole subtree from the source: one `memcpy` into each array, plus
  a rebase of `subtree_end` and the `Range` fields by the destination offset.
  The children are neither visited again nor re-emitted one at a time.
+ Otherwise emit the node, then the rewritten children individually.

The consequences, stated as costs, since "fast" is not a design:

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Case*], [*Cost*], [*Note*]),
  [A filter that matches nothing],
  [one `memcpy` per array],
  [The root reports no change, so the whole document copies as one contiguous
    block. An identity filter runs at memory bandwidth.],

  [A filter that rewrites `k` nodes],
  [`O(k · d + m)`],
  [`d` is depth, `m` the total size of the `k` rewritten subtrees. Only the
    spine from each rewritten node to the root is rebuilt node by node; every
    sibling branch is a `memcpy`.],

  [A tag-scan filter],
  [`O(n)` bytes `+` the above],
  [The scan reads one byte per node, not twenty-one.],

  [A pipeline of `s` filters],
  [`s` passes],
  [Each produces a new tree in the arena. Nothing is freed between stages; the
    arena is released once at the end.],
)

The rebase step deserves a note because a bug there would be silent. A copied
subtree's internal indices are all relative to the source array; adding the
destination offset to `subtree_end` and to every `Range` pointing within the
copied region is correct precisely because a subtree is *contiguous and
self-contained* — no node inside it can point outside it except through the
side tables, which are copied wholesale and never renumbered. The validator
runs after every stage, so a rebase error fails immediately rather than
producing a plausible wrong document.

== Complexity summary

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Operation*], [*Cost*], [*Why*]),
  [Read a node], [`O(1)`], [Array index.],
  [Iterate children], [`O(children)`], [Hop `subtree_end`.],
  [Skip a subtree], [`O(1)`], [Assign `subtree_end`.],
  [Find all nodes of a tag], [`O(n)` bytes], [Vectorized scan of the tag column.],
  [Copy a subtree], [`O(size)` `memcpy`], [Contiguous.],
  [Full traversal], [`O(n)`], [Linear scan; preorder is document order.],
  [Filter stage, `k` edits], [`O(k · d + m)`], [Spine rebuild plus edited subtrees.],
  [Depth of any operation], [`≤ max_depth`], [Checked, not assumed.],
)

= Filters

== The `build.zig` analogy, taken literally

Zig's build system is configured by a Zig file in the user's project that
imports `std.Build`, declares a graph through a typed API, and is compiled and
run by the toolchain. It is not a configuration format and not a scripting
language; it is a program, with a compiler checking it.

zenfmt filters work the same way. A user writes a Zig file that imports the
`zenfmt` module, declares a pipeline through a typed API, and compiles it into
a binary:

```zig
// filters.zig, in the user's own project
const std = @import("std");
const zenfmt = @import("zenfmt");

pub fn filters(p: *zenfmt.Pipeline) void {
    // One that ships with zenfmt.
    p.add(zenfmt.filters.shift_headings, .{ .by = 1 });

    // One the user wrote, in this file or beside it.
    p.add(InternalLinks, .{ .base = "https://docs.example.com/" });

    // Order matters, and is exactly the order written here.
    p.add(zenfmt.filters.drop_empty_divs, .{});
}

const InternalLinks = struct {
    pub const name = "internal-links";
    pub const description = "Rewrite bare `#anchor` targets to absolute URLs";
    pub const matches: []const zenfmt.InlineTag = &.{.link};

    base: []const u8,

    pub fn visitInline(
        f: *@This(),
        ctx: *zenfmt.Filter.Context,
        node: u32,
    ) !zenfmt.Filter.Action {
        const target = ctx.linkTarget(node);
        if (!std.mem.startsWith(u8, target, "#")) return .keep;

        const absolute = try ctx.fmt("{s}{s}", .{ f.base, target[1..] });
        try ctx.openLink(absolute, ctx.linkTitle(node));
        try ctx.emitChildren(node);
        ctx.close();
        return .replaced;
    }
};
```

```sh
zig build           # produces a zenfmt binary carrying these filters
zenfmt --filters manual.docx -o manual.md
```

Everything a filter does is type-checked, there is no serialization boundary,
and a filter costs a direct call — the pipeline is an `inline for` over the
registered stages. The tradeoff is stated plainly under _Alternatives
Considered_: this buys speed and safety at the cost of requiring a Zig
toolchain to write a filter, where pandoc requires only a Lua interpreter.

== The filter contract

A filter is a Zig type with a name, optional options fields, and one or both
visit methods.

```zig
pub const Filter = struct {
    pub const Order = enum {
        /// Children are visited before their parent. The default, and what a
        /// filter that rewrites leaves into containers wants.
        bottom_up,
        /// The parent is visited first; returning `.drop` or `.replaced`
        /// means its children are never visited.
        top_down,
    };

    pub const Action = enum {
        /// Emit this node unchanged, with its rewritten children. When no
        /// descendant changed, this is the `memcpy` fast path.
        keep,
        /// Emit nothing: the node and its subtree disappear.
        drop,
        /// Emit the node's children in its place, without the node itself.
        unwrap,
        /// The filter has already emitted a replacement into `ctx`.
        replaced,
    };

    pub const Context = struct {
        gpa: std.mem.Allocator,
        /// The tree being read. Immutable for the duration of the stage.
        in: *const Document,
        /// The tree being written. Filters emit replacements here.
        out: *Builder,
        reports: *Reports,
        limits: Limits,

        // Inspection: O(1), or a bounded scan.
        pub fn blockTag(ctx: *Context, node: u32) BlockTag;
        pub fn inlineTag(ctx: *Context, node: u32) InlineTag;
        pub fn textOf(ctx: *Context, node: u32) []const u8;
        pub fn hasClass(ctx: *Context, node: u32, class: []const u8) bool;
        pub fn attribute(ctx: *Context, node: u32, key: []const u8) ?[]const u8;
        pub fn children(ctx: *Context, node: u32) Children;

        // Emission, for the `.replaced` action.
        pub fn emitChildren(ctx: *Context, node: u32) !void;
        pub fn emitCopy(ctx: *Context, node: u32) !void;
        pub fn emitStr(ctx: *Context, bytes: []const u8) !void;
        pub fn open(ctx: *Context, tag: InlineTag, a: Attrs) !void;
        pub fn close(ctx: *Context) void;
        // ... and the block equivalents

        /// Formats into the arena. The result lives as long as the tree.
        pub fn fmt(ctx: *Context, comptime f: []const u8, args: anytype) ![]const u8;

        /// Reports a transformation the user should know about, in the same
        /// Elm form readers and writers use.
        pub fn report(ctx: *Context, r: Report) !void;
    };
};
```

The contract:

- *A filter may assume* the input tree satisfies every invariant, that `in`
  does not change while the stage runs, and that the arena outlives the call.
- *A filter must* leave the builder balanced, respect `limits`, and be
  deterministic — the same input tree must produce the same output tree.
- *A filter must not* write to the output stream, read the filesystem or the
  network, depend on the input or output format, or retain an index from `in`
  past the end of its stage.
- *The engine guarantees* it validates the tree after every stage, so a filter
  producing a structurally invalid tree fails at its own stage rather than
  corrupting a later one.

The prohibition on format knowledge is the important one. A filter that behaves
differently for DOCX input is a reader bug wearing a disguise; the whole point
of the tree is that a transform written against it works for every format that
can reach it.

== Filters that ship

A small set, chosen because they are the transforms people actually reach for
and because each exercises a different part of the contract:

#tbl(
  columns: (auto, 1fr),
  table.header([*Filter*], [*What it does, and what it demonstrates*]),
  [`shift-headings`],
  [Adds a constant to every heading level, clamping at 1 and 6. The simplest
    possible stage: one tag, an `attr` edit, `.replaced`.],
  [`promote-first-heading`],
  [Moves a leading level-1 heading into document metadata as the title. Shows
    a filter that edits the document as a whole rather than node by node.],
  [`drop-empty-divs`],
  [Unwraps `div` and `span` nodes carrying no attributes. Demonstrates
    `.unwrap`, and is genuinely useful after HTML and DOCX ingestion.],
  [`flatten-nested-tables`],
  [Replaces a table inside a table cell with a placeholder and a report. The
    canonical lossy transform, and the one that shows how a filter cooperates
    with the diagnostics contract.],
  [`strip-classes`],
  [Removes classes matching a pattern. Shows attribute editing and the
    tag-scan fast path.],
)

Each is under 150 lines, and they double as the worked examples in the book and
as the tests for the filter machinery.

= The Plugin Contract

== Readers

A reader is a Zig file exporting one public type with a `read` function and two
comptime declarations.

```zig
pub const DocxReader = struct {
    pub const format: Format = .docx;
    /// How the engine presents the input. `.bytes` receives the whole file in
    /// memory; `.seekable` receives a file handle, which container formats
    /// need because they read a central directory before anything else.
    pub const input_mode: InputMode = .seekable;

    pub fn read(ctx: *ReadContext) ReadError!void { ... }
};

pub const ReadContext = struct {
    gpa: std.mem.Allocator,
    io: std.Io,
    out: *Builder,
    input: Input,
    reports: *Reports,
    limits: Limits,
    options: Options,
};
```

- *A reader may assume* the builder is empty, the arena outlives the call, the
  input is complete, and the engine validates the result.
- *A reader must* leave the builder balanced, respect `limits`, produce valid
  UTF-8, use the canonical nesting order when converting flag sets, and report
  every construct it recognized and chose not to represent.
- *A reader must not* write to the output stream, read a file it was not given,
  resolve a network reference, or call `std.debug.print`.
- *The engine guarantees* it frees everything the reader allocated, and that a
  reader error aborts before any output byte is written — a failed conversion
  never leaves a half-written file.

== Writers

```zig
pub const MarkdownWriter = struct {
    pub const format: Format = .markdown;
    pub fn write(ctx: *WriteContext) WriteError!void { ... }
};

pub const WriteContext = struct {
    gpa: std.mem.Allocator,
    doc: *const Document,
    out: *std.Io.Writer,
    reports: *Reports,
    limits: Limits,
    options: Options,
};
```

- *A writer may assume* every invariant holds. It does not defensively check
  structure; a violation is an engine bug the validator catches upstream.
- *A writer must* handle every tag — the switch is exhaustive with no `else`,
  so adding a node to the AST is a compile error in every writer rather than a
  silent omission at runtime. This is the main reason the tags are a closed
  enum.
- *A writer must* report any construct it cannot express, and produce
  byte-identical output for identical input.
- *A writer must not* allocate per node or buffer the whole output.

Note the asymmetry with readers: a reader may skip a construct silently if its
ZDS records the omission, while a writer may not skip a *tag* at all. It may
degrade a construct — a GFM table cell holding two paragraphs must be
flattened — but deliberately, and it must say so.

The `anytype` writer parameter of the preliminary sketch is replaced by
`*std.Io.Writer`. Zig 0.16's `Io.Writer` is already the type-erased vectored
interface, so `anytype` would buy nothing and would monomorphize each writer
per destination for no benefit.

= The Registry and the Static Router

== One table

`src/registry.zig` is the only file edited when a plugin is added, and it holds
tables rather than switches. A switch answers one question; the CLI needs
several — which formats exist, which extensions map to which, what to print for
`--list-formats`, what to suggest when a name is misspelled — and they must not
drift apart.

```zig
pub const ReaderEntry = struct {
    id: Format,
    Plugin: type,
    extensions: []const []const u8,
    description: []const u8,
};

pub const readers = [_]ReaderEntry{
    .{
        .id = .docx,
        .Plugin = @import("docx_reader.zig").DocxReader,
        .extensions = &.{"docx"},
        .description = "Office Open XML word processing document",
    },
    // ... one entry per input format
};

pub const writers = [_]WriterEntry{ ... };
pub const builtin_filters = [_]FilterEntry{ ... };
```

A comptime block in the same file checks the tables: no duplicate id, no
extension claimed twice, and every plugin's own `format` declaration matching
the row it is registered under. These are the mistakes a table invites, and
catching them in the compiler costs nothing.

== Dispatching a runtime pair into a comptime matrix

The CLI learns its formats from `argv`, so a purely comptime `getReader` cannot
serve it — the preliminary sketch's version raised `@compileError` for
unregistered ids, which is right for a library caller and unusable for a tool.
The bridge is an unrolled search:

```zig
pub fn convert(e: *Engine, from: Format, to: Format, input: Input, out: *Writer) Error!void {
    inline for (registry.readers) |r| {
        if (r.id == from) {
            inline for (registry.writers) |w| {
                if (w.id == to) return e.convertStatic(r.Plugin, w.Plugin, input, out);
            }
            return error.UnsupportedOutputFormat;
        }
    }
    return error.UnsupportedInputFormat;
}

/// The zero-dispatch entry point, for callers who know both formats.
pub fn convertStatic(
    e: *Engine,
    comptime Reader: type,
    comptime Writer: type,
    input: Input,
    out: *std.Io.Writer,
) Error!void { ... }
```

Whether the matrix explodes the binary is a fair question, and the answer is no
for a structural reason: `convertStatic` is `Reader.read`, then the filter
pipeline, then `Writer.write`, with the AST between them. Each reader and each
writer is instantiated once — `N + M` bodies — and only the call glue is
`N × M`, at a handful of instructions per cell. The AST boundary buys this, and
it is a second reason to have one.

== Format taxonomy and roadmap

The registry grows along four families. Markdown is the default writer and the
only one in the first release.

#tbl(
  columns: (auto, 1fr, auto),
  table.header([*Family*], [*Formats*], [*Phase*]),
  [Office], [DOCX, XLSX, PPTX, RTF], [4–5],
  [OpenDocument], [ODT, ODS, ODP], [5],
  [Lightweight markup],
  [Markdown (CommonMark + GFM), AsciiDoc, reStructuredText, Org, Textile,
    MediaWiki],
  [2, 6],
  [Data and web], [CSV, TSV, JSON, HTML, EPUB], [2, 6],
)

The lightweight markup family is where the AST earns its keep in a way the
office formats do not exercise. AsciiDoc admonitions, reStructuredText
directives, and Org drawers are all block-level constructs with no dedicated
node; they map to `div` with a class, which is exactly what `div` is for, and
they are the reason it is in the node set from the start rather than added when
the first of them arrives.

== Format detection

Resolved in this order, first match winning: an explicit `--from` or `--to`;
the file extension against the registry's lists; content sniffing
(`PK\x03\x04` followed by `[Content_Types].xml` for OOXML, whose specific
format then comes from the content-type declarations; `{\rtf` for RTF; a `%PDF`
header rejected with a clear message); Markdown for output with neither flag
nor extension. Otherwise an error naming the formats that were available —
never a silent fallback to plain text, which produces baffling output from a
misdetected binary.

= Memory Model

*One arena per conversion.* Every allocation — both node arrays, the text pool,
the side tables, reader scratch, and every intermediate tree the filter
pipeline produces — comes from a single `std.heap.ArenaAllocator` created by
the engine and destroyed when the conversion returns. Nothing is individually
freed and no destructor runs.

This is not only a simplification. It removes use-after-free and double-free
from the plugin surface entirely, which matters because plugins are the part of
the system most likely to be written by someone who has not read this record: a
reader cannot leak, because it does not own anything. It is also what makes the
filter pipeline's copy-per-stage affordable — the stages are not freed
individually because they are not freed at all until the end.

*Growth.* Arrays grow geometrically, and readers that can estimate their output
call `ensureTotalCapacity` up front. The engine seeds the estimate from the
input size using per-format ratios in the registry, so the common case is one
allocation per array for the whole conversion.

*Budgets.*

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Quantity*], [*Target*], [*Rationale*]),
  [Allocations per conversion], [`O(log n)`],
  [Array growth only. Zero per node or per byte of text.],
  [Bytes per node], [21], [Struct-of-arrays, so no padding waste.],
  [Peak memory, text formats], [`≤ 5×` input],
  [Text pool ≈ input, plus the node arrays. Measured, not assumed.],
  [Peak memory per filter stage], [`≤ 1×` tree],
  [The output tree. Prior stages remain in the arena, so a pipeline of `s`
    filters peaks at `s + 1` trees. The CLI reports this, and `--filters` is
    the only way to incur it.],
  [Writer memory], [`O(depth)`],
  [Writers stream. The only state is the open-container stack, bounded by
    `max_depth`.],
)

These are targets, enforced by a benchmark that records measured numbers to a
result file. Following the practice inherited with this documentation tree: a
number in a table comes from a recorded result file, never from a keyboard.

= Diagnostics and Error Messages

An error message is a user interface, and most converters have a bad one. The
target here is the standard Elm set: say what happened in plain language, show
the input that caused it, and say what to do about it. A bare error code is a
defect.

== The report

```zig
pub const Severity = enum { note, warning, err };

pub const Report = struct {
    severity: Severity,
    /// Short and unique: "UNKNOWN INPUT FORMAT". The banner, and the stable
    /// identifier used for suppression and in tests.
    title: []const u8,
    /// One or two sentences, in the first person, saying what happened.
    summary: []const u8,
    /// The offending input with a highlighted span, when there is one.
    excerpt: ?Excerpt,
    /// What to do about it.
    hint: ?[]const u8,
    /// Concrete alternatives, when a name was not recognized.
    suggestions: []const []const u8,
    /// How many times this report fired. Repeats are counted, not repeated.
    count: u32,
};
```

Rendering rules: a rule-to-margin banner carrying the title and the source
name; prose wrapped to the terminal width; an excerpt with line numbers and a
caret span; the hint last. Color only when the destination is a terminal, so
piped output stays diffable. Reports aggregate by title, so a document with
four hundred comments produces one line reporting four hundred rather than four
hundred lines.

== What it looks like

An unrecognized format name, with the nearest match by edit distance:

```
-- UNKNOWN INPUT FORMAT --------------------------------------- zenfmt

I do not recognize `docs` as an input format.

    zenfmt --from docs report.docx
                  ^^^^

Did you mean `docx`?

These are the input formats I know:

    asciidoc   csv    docx   html   markdown
    odt        rst    rtf    text   xlsx
```

A limit refusal, which must explain itself, because the honest response to a
zip bomb is a refusal the user can understand and — if they are sure —
override:

```
-- ARCHIVE EXPANDS TOO FAR ------------------------------ handbook.docx

The entry `word/document.xml` expanded to 214 MB from 486 KB, a ratio of
451:1. I stopped at the 200:1 limit.

A ratio this high is usually a file built to exhaust the memory of the
program reading it. It can also be a legitimate document with a very
large amount of repeated content.

If you trust this file, raise the limit for this run:

    zenfmt --limit max_compression_ratio=600 handbook.docx
```

A structural problem in the source, shown in context, with what was done about
it:

```
-- MISMATCHED TABLE ROW -------------------------------- quarterly.docx

Row 7 of the table starting on line 412 has 5 cells, but the table
declares 4 columns.

    405 | <w:tblGrid>
    406 |   <w:gridCol w:w="2400"/>        4 columns declared here
        |   ...
    412 | <w:tr>
    417 |   <w:tc>                         this is the 5th cell
        |   ^^^^^^

I kept the extra cell and widened the table to 5 columns. A Markdown
table must be rectangular, so every other row now ends with an empty
cell.
```

A lossy conversion, reported at the end of a successful run:

```
-- CONVERTED WITH LOSSES -------------------------------- handbook.docx

The conversion succeeded. These constructs have no Markdown equivalent
and were dropped:

    412  comments
     38  tracked-change deletions
      6  text boxes
      2  embedded objects (1 chart, 1 spreadsheet)

Run with --strict to make this an error instead.
```

== The lossiness tiers

The tier of a construct is decided in the plugin's ZDS, not by the implementer
at the keyboard.

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Tier*], [*Emits*], [*Meaning*]),
  [Represented], [nothing], [The construct survives into the AST.],
  [Degraded], [`note`],
  [Something reached the output in a simplified form: a multi-paragraph table
    cell flattened, a nested table inlined, a font choice reduced to `code`.
    The plugin's record states which construct degrades to which node.],
  [Dropped], [`warning`],
  [Recognized and produced nothing: comments, tracked-change deletions,
    headers and footers, embedded objects. The user is told what and how
    many.],
)

An unrecognized construct is not a fourth tier — it is a `note` titled
`UNHANDLED CONSTRUCT` naming the element, so an unimplemented case is visible
in the field rather than silent. This is the mechanism that distinguishes a
decision from a gap at runtime, as the omissions table does at review time.

`--strict` promotes warnings to errors and exits non-zero; `--quiet`
suppresses notes; `--reports=json` emits structured records for a script
driving a bulk conversion.

= Reading the Office Formats

== The container: OOXML and ODF are ZIP archives

DOCX, XLSX, PPTX, and the ODF family are ZIP archives of XML parts. One
`zip.zig` serves all of them, and it is the component that most needs its
limits specified, because it is where hostile input does the most damage for
the least effort.

The reader works from the central directory at the end of the archive — which
is why these plugins declare `input_mode = .seekable`. It never walks local
file headers to discover entries, the parsing mode ZIP-confusion attacks
exploit, and it never expands an entry it was not asked for. A DOCX conversion
typically touches four entries out of several dozen.

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Limit*], [*Default*], [*What it prevents*]),
  [`max_archive_entries`], [4,096],
  [A directory with millions of entries exhausting memory before any entry is
    read.],
  [`max_entry_uncompressed`], [256 MiB], [One entry expanding without bound.],
  [`max_total_uncompressed`], [1 GiB], [Many entries each individually under the cap.],
  [`max_compression_ratio`], [200:1],
  [The classic zip bomb, refused during streaming rather than after expansion
    completes.],
  [`max_entry_name_bytes`], [1,024], [Pathological names.],
)

Three rules have no override, because there is no legitimate use: an entry name
that is absolute, contains a `..` component, contains a backslash, or contains
a NUL rejects the archive; encrypted entries are refused with a clear message;
only `stored` and `deflate` are accepted.

== The XML layer

`xml.zig` is a pull parser shared by every XML-based format, returning events
rather than building a tree, so peak memory is proportional to depth rather
than document size. Its security posture is a short list, and all of it is
refusal:

- *No DTD processing whatsoever.* A `DOCTYPE` declaration rejects the document.
  This makes entity-expansion attacks structurally impossible rather than
  bounded. No office format has a legitimate reason to carry a DTD.
- *No external entities, no `xinclude`*, and no filesystem or network
  resolution of any reference. The parser has no I/O.
- *The five predefined entities and numeric character references only.*
  References above the Unicode range or in the surrogate range are errors.
- *`max_xml_depth`*, default 256, bounding the explicit stack.
- *Namespace prefixes are resolved to URIs*, and elements matched on the URI. A
  document binding `w:` to something other than the WordprocessingML namespace
  does not get to impersonate one.

== DOCX

#tbl(
  columns: (auto, auto, 1fr),
  table.header([*Source construct*], [*AST result*], [*Notes*]),
  [`w:p`], [`para`], [The default when no other rule applies.],
  [`w:p` with a heading `w:pStyle`], [`heading`, level in `attr`],
  [Resolved through `styles.xml`: the built-in `Heading1`..`Heading9`, and any
    style whose `w:basedOn` chain reaches one. Levels above 6 clamp, with a
    note.],
  [`w:p` with `w:numPr`], [`list_item` in a synthesized list],
  [The hardest mapping; see below.],
  [`w:r` with `w:rPr` flags],
  [nested `strong`, `emph`, and the rest, in canonical order],
  [The flag-to-nesting conversion. A toggle with `w:val="0"` clears rather
    than sets.],
  [`w:t`], [`str` and `space` nodes], [`xml:space="preserve"` is honored.],
  [`w:rPr/w:vertAlign`], [`superscript` / `subscript`], [],
  [`w:rPr/w:rFonts` naming a monospace family], [`code`],
  [Matched against known monospace families. Degraded, with a note: the source
    expressed a font, the AST expresses a role.],
  [`w:br`], [`line_break`], [`w:type="page"` dropped with a note.],
  [`w:tab`], [`space`], [Markdown has no tab semantics.],
  [`w:hyperlink`], [`link`],
  [`r:id` resolved through `word/_rels/document.xml.rels`; an anchor-only link
    becomes a fragment target.],
  [`w:tbl` / `w:tr` / `w:tc`], [`table` / `table_row` / `table_cell`],
  [Header rows go under `table_head`, the rest under `table_body`.],
  [`w:tcPr/w:gridSpan`, `w:vMerge`], [cell spans],
  [Continuation cells fold into the originating cell.],
  [`w:drawing`, `w:pict`], [`image`],
  [The relationship target is recorded in `media`; bytes are not extracted in
    the first release.],
  [`w:footnoteReference`], [`note`],
  [The body comes from `footnotes.xml` and is appended outside `body`.],
  [`w:sdt`], [`div` with a class],
  [The content control's tag becomes the class, rather than being unwrapped
    and lost. This is `div` doing the job it exists for.],
  [`w:ins`], [content kept], [Tracked insertions accepted.],
  [`w:del`], [dropped], [Tracked deletions rejected, with a warning naming the count.],
  [`w:instrText`], [dropped except `HYPERLINK`], [Field codes are computed values zenfmt cannot evaluate.],
)

=== Numbering, the hard case

DOCX has no list element. A list is a maximal run of consecutive `w:p`
paragraphs each carrying a `w:numPr` with a `w:numId` and a `w:ilvl`, where
`numId` points through `numbering.xml` to an abstract definition saying whether
each level is a bullet or a number and where it starts. The reader must infer
the structure:

+ Accumulate consecutive numbered paragraphs sharing a `numId`.
+ Open a list when an `ilvl` first appears, and a nested list inside the
  current `list_item` when `ilvl` increases.
+ Close lists when `ilvl` decreases, when `numId` changes, or when a paragraph
  without `w:numPr` intervenes.
+ Take ordered-versus-bullet, the number style, and the start from the abstract
  definition for that level, not from the paragraph.
+ An `ilvl` jumping by more than one opens the intervening levels as empty
  items, because the AST requires a list to contain `list_item`.

Tightness has no DOCX representation. Lists read from DOCX are marked tight,
which round-trips more cleanly through Markdown, and the choice is recorded
here so it is not rediscovered as a bug.

=== Deliberate omissions

Recognized and dropped, each with a warning: comments and comment ranges;
tracked-change deletions and formatting revisions; headers, footers, and page
numbering; section properties, page size, margins, and columns; explicit page
and column breaks; fonts, sizes, colors, and highlighting beyond the nodes
above; text boxes, shapes, and SmartArt; embedded OLE objects; bookmarks and
cross-reference fields; and revision save IDs.

Deferred rather than dropped: OMML mathematics — the `math` node exists, so
this is a mapping to write rather than a node set to change — and image byte
extraction, where only the extraction is absent.

== The other formats

#tbl(
  columns: (auto, 1fr),
  table.header([*Format*], [*Approach and principal difficulty*]),
  [ODT / ODS / ODP],
  [Same container and XML machinery. `text:h` carries its level in
    `text:outline-level`, easier than DOCX. Character styles are the hard
    part: `text:span` names a style resolved through `office:automatic-styles`
    and `styles.xml`, following `style:parent-style-name` chains, to learn
    whether `fo:font-weight` is bold. Lists are explicit, which removes the
    DOCX inference problem entirely.],
  [RTF],
  [Neither XML nor a container: a brace-delimited group language. A group
    stack carrying character state, `\b` and `\i` as toggles inherited by
    nested groups, `\par` ending a paragraph, `\'hh` hex escapes in the code
    page named by `\ansicpg`, `\uN` with its skip-count convention, and
    destination groups introduced by `\*` skipped wholesale. RTF in the wild
    comes from dozens of producers with incompatible habits, so the reader is
    error-tolerant by design: an unknown control word is skipped with a note
    rather than failing the document.],
  [XLSX / ODS],
  [Each sheet becomes a `heading` naming it, followed by a `table`. Cell text
    usually lives in `sharedStrings.xml`. Number formats are applied for dates
    and percentages, since a raw serial date would be worse than useless.
    Formulas are not evaluated; the cached value is used, with a note when
    absent. Sparse sheets must be materialized to keep rows rectangular.],
  [PPTX / ODP],
  [Each slide becomes a `heading` from the title placeholder followed by the
    body placeholders. Speaker notes append as a `div` with class `notes`.
    Positioning, animation, and non-text shapes are dropped. A presentation
    loses the most in this projection, and the reports say so loudly.],
  [Markdown],
  [A CommonMark reader with the GFM extensions. As much a test instrument as a
    feature: with it and the Markdown writer, `read ∘ write ∘ read` can be
    checked for the fixed-point property that anchors the fuzz suite.],
  [AsciiDoc],
  [Blocks are delimited by run-length markers, and admonitions, sidebars, and
    open blocks map to `div` with a class. Attribute entries become document
    metadata. The `include::` directive is *not* followed — a converter that
    reads arbitrary files named by its input is a file-disclosure primitive —
    and the refusal is reported rather than silent.],
  [reStructuredText],
  [Indentation-structured, with directives and roles as the extension
    mechanism. Directives map to `div` and roles to `span`, both carrying the
    directive name as a class. Reference-style links need a second pass, since
    a target may be defined anywhere in the document.],
  [HTML],
  [A tolerant parser. The reason `div`, `span`, and `raw_inline` are in the
    node set, and the format most likely to produce deeply nested input, so it
    is the primary consumer of `max_depth`.],
  [CSV / TSV],
  [RFC 4180 with quoting, embedded newlines, and doubled quotes. One `table`
    with the first row as `table_head`. Note that the preliminary sketch's
    example reader — which emitted every field as its own paragraph and lost
    the final field of a file with no trailing newline — is not what ships.],
  [Plain text],
  [Blank-line-separated blocks become paragraphs; line endings normalized. The
    phase 1 plugin, which exists to exercise the pipeline end to end.],
)

= The Markdown Writer

The sole writer of the first release, and therefore the definition of what
zenfmt's output looks like.

*Dialect.* CommonMark plus the GFM extensions for tables, strikethrough, task
lists, and footnotes. `--markdown-dialect` is reserved for later variants; the
first release ships one.

*Escaping.* The minimum that preserves meaning at the position where text is
emitted, because over-escaping produces output that is correct and unreadable.
`#`, `-`, `+`, `>`, and a digit followed by `.` or `)` are escaped only at the
start of a line. `*` and `_` only where they would start or end emphasis, which
for `_` means only at a word boundary. `[`, `]`, and a `!` before a `[` always.
`|` only inside a table cell. Nothing inside a code span or block; instead the
fence is chosen longer than any backtick run in the content.

*Inline emission.* The writer walks the inline tree and emits a delimiter pair
per container node — which the tree makes trivial, and which was the awkward
part of the flat-run design it replaced. `**` for `strong` and `_` for `emph`,
because the mixed pair is unambiguous in positions where one character for both
is not; `~~` for `strikeout`; backticks for `code`, with the fence one longer
than the longest run inside; a trailing backslash for `line_break` rather than
two spaces, because trailing whitespace does not survive editors and diffs.

`underline` and `small_caps` have no CommonMark spelling. Their children are
emitted unstyled with a `STYLE DROPPED` note — the degradation tier, and the
reason that tier exists.

*Block emission.*

#tbl(
  columns: (auto, 1fr),
  table.header([*Node*], [*Output*]),
  [`heading`], [ATX, never Setext. The identifier is emitted as a GFM anchor when present.],
  [`para`], [Text, then a blank line. `plain` omits the blank line.],
  [`block_quote`], [`> ` on every line, including blank ones inside the quote.],
  [`bullet_list` / `ordered_list`],
  [`-` for bullets; the recorded number style and start for ordered lists.
    Nested content indented to the marker width. Tight lists have no blank
    lines between items; loose ones do.],
  [`code_block`],
  [Fenced with at least three backticks, longer if the content contains a
    longer run, with the first class as the language. Indented blocks are
    never emitted, because they interact badly with list indentation.],
  [`table`], [A GFM pipe table with an alignment row, padded to a common column width up to a configurable limit.],
  [`div`], [Its children, attributes dropped with a note — unless `--markdown-divs` selects fenced div syntax.],
  [`note`], [Collected and emitted at the end as GFM footnote definitions.],
  [`horizontal_rule`], [`---`.],
  [`raw_block`], [Verbatim if its format is Markdown or HTML; dropped with a note otherwise.],
)

GFM table cells cannot contain block structure. A cell holding more than one
block, or any block that is not a paragraph, is flattened with a note; a nested
table becomes a placeholder and a warning. These are the honest failure modes
of a pipe table, and the `flatten-nested-tables` filter exists so a user can
make the transformation explicit and inspect it instead.

*Determinism.* Byte-identical output for identical input, across platforms and
build modes: `\n` always, never a trailing space, exactly one blank line
between blocks, exactly one newline at end of file, no hash-ordered iteration,
and no locale-dependent formatting. A golden-file suite is worthless without
this, and the property is cheap to hold if it is decided at the start.

= Repository and Build Layout

`src/` is flat. The preliminary sketch stated the TigerBeetle principle — the
layout is kept completely flat, with no deeply nested sub-packages — and then
drew `src/core/` and `src/plugins/`. The principle is right and the drawing is
not. Two directories with a handful of files each organize nothing a filename
prefix could not, and they add a `../` to every import. Flatness also makes the
file size limit do real work: a file that outgrows it must be split into a
genuinely separate concern rather than tucked into a subdirectory.

```
zenfmt/
├── build.zig               # library, CLI, tests, and the zds-* steps
├── build.zig.zon           # the `zenfmt` package
├── src/                    # the library module, flat
│   ├── root.zig            # public API: Engine, Format, Document, Pipeline
│   ├── ast.zig             # Block, Inline, Document, validate
│   ├── builder.zig         # Builder, the open-node stack, interning
│   ├── attr.zig            # the tag-to-attribute encoding, in one place
│   ├── walk.zig            # bounded walkers, tag scans, subtree copy
│   ├── engine.zig          # the static router and the arena lifecycle
│   ├── pipeline.zig        # the filter pipeline and the rebuild transform
│   ├── registry.zig        # THE table: one row per plugin
│   ├── report.zig          # Report, Excerpt, and the Elm-style renderer
│   ├── limits.zig          # every resource ceiling and its default
│   ├── zip.zig             # central-directory archive reader
│   ├── xml.zig             # pull parser: no DTD, no entities
│   ├── text_reader.zig
│   ├── markdown_reader.zig
│   ├── markdown_writer.zig
│   ├── docx_reader.zig     # with docx_styles.zig and docx_numbering.zig
│   ├── odt_reader.zig
│   ├── rtf_reader.zig
│   ├── asciidoc_reader.zig
│   ├── rst_reader.zig
│   ├── filter_shift_headings.zig
│   ├── filter_drop_empty_divs.zig
│   └── filter_flatten_tables.zig
├── cli/                    # its own package, depends on ../ by path
│   ├── build.zig
│   ├── build.zig.zon
│   └── src/main.zig
├── tests/
│   ├── trees.zig           # input to expected AST, no writer involved
│   ├── golden.zig          # input to expected output
│   ├── filters.zig         # tree to expected tree
│   ├── roundtrip.zig       # the fixed-point property
│   ├── fuzz.zig            # per-reader and per-filter fuzz targets
│   └── corpus/
├── examples/
│   └── filters/            # a user project showing the build.zig pattern
├── tools/zds.zig
└── docs/
```

*Two packages.* The root package is the `zenfmt` library. `cli/` is a separate
package depending on it by path, which buys two things: a library consumer
takes only the library, and the CLI is forced to be an ordinary consumer of the
public API rather than reaching into internals. If the CLI can only do what a
user's program can do, the API is adequate by construction — and because a
user's filter project depends on that same module, the guarantee is
load-bearing rather than aesthetic.

Zig has no formal workspace concept, so the root `build.zig` delegates to the
sub-package by running `zig build` in its directory.

*Build steps.* Alongside the ZDS steps from ZDS 0001: `zig build` for the
library and binary, `test`, `fuzz`, `bench`, `docs` for autodoc, and
`fmt-check`.

= Command-Line Interface

```
zenfmt [options] [input]

  -f, --from FORMAT        Input format. Default: from the extension, then
                           from content.
  -t, --to FORMAT          Output format. Default: markdown.
  -o, --output PATH        Output file. Default: stdout.
      --filters            Run the pipeline compiled into this binary.
      --list-formats       Print the registry's readers and writers.
      --list-filters       Print the filters compiled into this binary.
      --strict             Promote warnings to errors; exit non-zero.
      --quiet              Suppress notes.
      --reports=FORM       text (default) or json.
      --limit NAME=VALUE   Override one resource limit.
  -h, --help
  -V, --version
```

Reading from stdin is supported for formats whose `input_mode` is `.bytes`. A
container format needs to seek, so `zenfmt -f docx` from a pipe spills to a
temporary file and says so, rather than failing.

Argument parsing allocates nothing: flags match a comptime table derived from
the same declarations that generate `--help`, and values are slices of `argv`.
Exit codes are `0` success, `1` conversion error, `2` usage error, and `3`
limit exceeded — distinguished because a bulk script wants to treat a zip bomb
differently from a malformed document.

= Coding Standard

The style follows TigerBeetle's, because its rules are chosen for exactly this
situation: a program that parses untrusted input, must not crash, and must stay
readable for years.

#tbl(
  columns: (auto, 1fr),
  table.header([*Rule*], [*How it applies here*]),
  [*Assert liberally*],
  [Every function asserts its preconditions and postconditions; at least two
    assertions in any non-trivial function. The AST invariants are the richest
    source: a walker asserts `subtree_end` monotonicity as it advances, and the
    builder asserts stack balance on every close. Assertions are on in `Debug`
    and `ReleaseSafe`, and the released binary is `ReleaseSafe`.],
  [*No recursion*],
  [No traversal, parser, or writer recurses. Each keeps an explicit stack
    bounded by `max_depth`. A safety rule before a style rule: nesting depth is
    attacker-controlled, and a bounded stack turns a crash into a report.],
  [*Bound every loop*],
  [Every loop has a known upper bound, and the bound is asserted. A parser loop
    that could fail to advance asserts that its cursor moved.],
  [*Allocate at the boundary*],
  [TigerBeetle allocates everything at startup. A converter cannot know its
    document sizes in advance, so the adaptation is: one arena per conversion,
    sized from the input, with no allocation in any inner loop and none per
    node. The deviation is deliberate, and recorded here rather than left
    implicit.],
  [*Small functions, small files*],
  [Functions under 70 lines, files under 1,000. `docx_reader.zig` is already
    known to need splitting into `docx_styles.zig` and `docx_numbering.zig`,
    and the split is decided in advance rather than after the file overflows.],
  [*Explicit types and names*],
  [`u32` indices rather than `usize`, so a node index is a distinct thing from
    a byte offset. `snake_case` variables, `camelCase` functions, `PascalCase`
    types. No abbreviation that is not already in the format specifications.],
  [*Zero technical debt*],
  [A change lands complete: with its tests, its diagnostics, and its ZDS
    updated. There is no "clean this up later" state in this repository.],
)

= Testing Strategy

#tbl(
  columns: (auto, 1fr),
  table.header([*Layer*], [*What it establishes*]),
  [AST validator],
  [Runs on every conversion in `Debug` and `ReleaseSafe`, after every filter
    stage, in every test, and on every fuzz iteration. The oracle: a plugin
    that produces a structurally impossible tree fails even when nothing
    crashes.],
  [Tree tests],
  [`tests/trees.zig` asserts the AST a reader produces, with no writer
    involved. The only way to test a mapping without conflating it with the
    writer's choices, and the layer at which a format record's mapping table is
    verified row by row.],
  [Golden files],
  [Input and expected output. The regression net, and the artifact a reviewer
    reads to see what a mapping decision does. Updated only by an explicit
    `--update-goldens` run, so a change to output is always visible in a
    diff.],
  [Filter tests],
  [Input tree, filter, expected tree. Plus two properties every filter is
    checked against: an identity filter produces byte-identical arrays, and
    running a filter twice equals running it once for filters that declare
    themselves idempotent.],
  [Round-trip fixed point],
  [Markdown → AST → Markdown must be idempotent from the second pass onward.
    The first pass may normalize; the second must change nothing. A cheap,
    mechanically checkable property that catches a large class of writer
    bugs.],
  [Fuzzing],
  [`std.testing.fuzz` over each reader and each filter, with the validator as
    oracle. Properties: never crash, never exceed the limits, never fail to
    terminate, always leave the builder balanced. Seeded from the golden
    corpus.],
  [Adversarial corpus],
  [Checked-in zip bombs, quadratic-entity XML, traversal entry names,
    truncated archives, encrypted entries, and pathologically nested HTML —
    each asserting the specific refusal, so a later relaxation of a limit fails
    a test rather than silently widening the attack surface.],
  [Report snapshots],
  [The rendered text of every diagnostic is a golden file. An error message is
    a user interface, and it regresses like one.],
  [Benchmarks],
  [Throughput, allocation counts, and the filter fast-path ratio, written to
    result files. Numbers quoted in any document come from those files.],
  [Differential],
  [Comparison against pandoc on the corpus where it is installed. Advisory,
    not a gate: a difference is a question, not a defect, since the two
    programs make different deliberate choices.],
)

= Security Considerations

The threat model is one sentence: an attacker supplies the input file, and
possibly a great many of them, to a zenfmt process converting documents on
someone else's behalf.

*Resource exhaustion* is the primary risk, addressed by the limits above, each
with a default recorded here, a CLI override, and a test asserting the refusal.
Ratio limits are checked during decompression rather than after, so a bomb is
refused while it is expanding.

*Memory safety* is Zig's to provide in `ReleaseSafe`, which is what the
released binary ships in. The design makes the guarantee cheap: no recursion
anywhere, explicit stacks bounded by `max_depth`, and bounds-checked slicing
throughout.

*Entity expansion* is not bounded but excluded: no DTD processing at all.

*Path traversal* cannot escape a directory, because zenfmt writes only its
output file. Archive entry names are validated anyway, because a name escaping
the archive namespace is evidence of a file built to confuse a consumer, and
refusing it is free.

*Reference following* is refused across the board: AsciiDoc `include::`,
reStructuredText `.. include::`, XML external entities, and HTML `src`
attributes are never resolved. A converter that reads files named by its input
is a file-disclosure primitive. Each refusal is reported rather than silent, so
a user converting a document that genuinely uses includes learns why the output
is incomplete.

*Content dangerous downstream* is deliberately out of zenfmt's hands: a link
target in the input becomes a link target in the output, unmodified and
unresolved. zenfmt never fetches a URL and does not sanitize one, because it
cannot know the destination's context. The documentation must say so where a
user will see it, and an HTML writer will need its own record on sanitization.

*Filters* run in-process with full program privileges. They are compiled from
source the user chose, exactly as `build.zig` is, and the trust model is the
same: running a filter is running a program. This is stated in the filter
documentation, because the `build.zig` analogy might otherwise suggest a
sandbox.

*Supply chain*: no third-party Zig dependencies in the first release.
`zip.zig` and `xml.zig` are written here rather than vendored — a real cost in
effort, and a real reduction in attack surface for a program whose entire job
is parsing untrusted input.

= Operational Considerations

A single static executable: no runtime dependencies, no configuration file, no
network access. It runs the same in a container, a CI job, and a shell.

For bulk conversion the relevant surfaces are the exit codes above,
`--reports=json`, and the guarantee that a failed conversion writes no output
file. A caller processing ten thousand documents can distinguish "malformed"
from "hostile" from "converted with losses you should look at" without parsing
prose.

Cross-compilation is expected to work for every supported target without
special handling: no C dependencies, and no platform-specific code outside the
CLI's file handling.

= Alternatives Considered

#tbl(
  columns: (auto, 1fr),
  table.header([*Alternative*], [*Why it was not chosen*]),
  [A flat inline layer of styled runs, with no inline nesting],
  [This record's own earlier draft. Rejected: filters need node identity, and
    `link`, `note`, `span`, and `cite` need children regardless. The argument
    is under _Why the tree is a tree_. What survives is the canonical nesting
    order required of flag-based readers.],
  [A pointer-based recursive tree, as pandoc has],
  [The natural expression of the AST, and what most implementations use.
    Rejected for storage only, not for structure: pointers forfeit contiguous
    subtrees, and contiguous subtrees are what make the filter rebuild a
    `memcpy` rather than a full copy. The tree shape is unchanged.],
  [Mutable in-place filters],
  [Faster in the abstract, and the obvious thing to want. Rejected: insertion
    into a preorder array is `O(n)`, aliasing between the tree a filter reads
    and the one it writes is a bug factory, and the rebuild with subtree
    sharing is already within a constant factor of in-place for realistic edit
    counts. Immutability also makes a stage trivially testable.],
  [Lua or another embedded scripting language for filters],
  [What pandoc does, and it lowers the barrier considerably. Rejected for the
    first release: an interpreter is a large dependency and a large attack
    surface, and the `build.zig` model gives type checking and native speed.
    The cost — a Zig toolchain to write a filter — is real, and recorded as an
    open question.],
  [External filters over a JSON protocol],
  [pandoc's other mechanism, and the one that would give access to its
    existing ecosystem. Not rejected but deferred: it needs a stable
    serialized form of the AST, a decision worth making after the node set has
    settled. The node set is deliberately pandoc-compatible so this stays
    cheap.],
  [Runtime plugin registration with vtables],
  [Would allow dynamically loaded formats and a smaller binary. Rejected: it
    forfeits the compile-time exhaustiveness check that makes adding a node a
    compile error in every writer, adds an indirect call per node, and buys a
    capability nobody asked for.],
  [Shelling out to pandoc, or binding to it],
  [Would deliver every format immediately. Rejected: it makes the project a
    wrapper, inherits a GHC runtime, and forfeits every performance and memory
    property specified here.],
  [Parent-index instead of `subtree_end`],
  [Simpler to build, since nothing is patched on close. Rejected: it makes
    "iterate the children of this node" a full scan, and loses the contiguous
    subtree property the filter system depends on.],
  [One node array for blocks and inlines together],
  [Would collapse the walker to a single code path. Rejected: it forfeits the
    type distinction pandoc draws, makes the tag column heterogeneous and so
    less useful for scanning, and would leave the validator's structural rules
    expressible only at runtime.],
  [Multiple writers in the first release],
  [Rejected deliberately. One writer means the AST is exercised against many
    readers and one consumer, the configuration in which its adequacy is
    easiest to judge. A second writer before the AST settles would harden the
    wrong decisions.],
)

= Corrections to the Preliminary Sketch

This design departs from the sketch that preceded it in eleven places.
Recording them explicitly is cheaper than having them rediscovered in review.

#tbl(
  columns: (auto, 1fr, 1fr),
  table.header([*\#*], [*Sketch*], [*This record*]),
  [1],
  [`src/core/` and `src/plugins/` subdirectories, alongside a stated principle
    of flatness.],
  [Flat `src/`, per the stated principle.],

  [2],
  [`Block` has no nesting: a flat list of blocks each pointing at a run of
    inlines.],
  [A nested block tree, stored in preorder with `subtree_end`. Blockquotes,
    nested lists, and table cells are otherwise unrepresentable, and every
    office format produces all three.],

  [3],
  [`Inline` has one tag per formatting kind, so one style per run.],
  [A nested inline tree using pandoc's node set. Containers wrap; `link`,
    `note`, `span`, and `cite` carry children.],

  [4],
  [No attributes on nodes.],
  [pandoc's `Attr` — identifier, classes, key-value pairs — on every node that
    has one in pandoc. It is how filters select, and how a format's structure
    without a dedicated node survives.],

  [5],
  [No transformation layer.],
  [A filter pipeline written in Zig in the `build.zig` manner, with a rebuild
    transform that shares unchanged subtrees by `memcpy`.],

  [6],
  [`extra: u32` with meaning by convention.],
  [A documented per-tag encoding in `attr.zig`, reached only through
    accessors.],

  [7],
  [`getReader` raises `@compileError` for unregistered formats, so dispatch
    must be comptime.],
  [Comptime tables plus an `inline for` router, so a runtime format pair from
    `argv` enters the comptime matrix.],

  [8],
  [`write(writer: anytype, ...)`],
  [`*std.Io.Writer`, already the type-erased interface in Zig 0.16.],

  [9],
  [`read(allocator, pool, src: []const u8)`],
  [A `ReadContext` carrying `io`, reports, limits, and options. Container
    formats need to seek, and every reader needs to report what it dropped.],

  [10],
  [The CSV example emits each field as its own paragraph, and loses the final
    field when the file has no trailing newline.],
  [CSV maps to one `table`, with RFC 4180 quoting.],

  [11],
  [No channel for lossiness or errors.],
  [Elm-style `Report`s with excerpts, hints, and suggestions; the three-tier
    lossiness contract; aggregation by title; `--strict`.],
)

Two ideas from the sketch are adopted unchanged and worth affirming: flat
data-oriented storage with `u32` offsets instead of a pointer graph, and
comptime plugin resolution that keeps the engine free of format knowledge.
Those are the load-bearing ideas, and this record elaborates them rather than
replacing them.

= Open Questions

== The cost of Zig-only filters

The `build.zig` model gives type checking, native speed, and no interpreter. It
also means writing a filter requires a Zig toolchain and a compile, where
pandoc requires a text editor and Lua. For a user who wants to shift heading
levels in one document, that is a steep gradient. Options, in increasing order
of cost: ship enough built-in filters that the common cases need no compile;
add a small declarative expression for select-and-rewrite rules covering
perhaps 60% of filters without a toolchain; add the pandoc JSON bridge. Which,
and when?

== A serialized AST format

A stable serialization would give external filters, a debugging dump, and a
cache. It also freezes the node set far more firmly than an internal
representation does. Worth defining now, while the node set can still change
cheaply, or after the first release?

== Metadata values as block ranges

`Meta.value` is a block range so a title with emphasis survives. That is right
for titles and wrong for a boolean or an author list, which pandoc models with
a proper `MetaValue` variant type. Does the first release need that, or is a
block range with a documented convention enough?

== Image bytes

`Media.bytes` is never filled in the first release. Should the release extract
images to a sidecar directory (`--extract-media`), or is recording the
archive-internal path enough for a Markdown-only release?

== Table alignment source

DOCX and ODT express alignment per paragraph; a GFM table has one alignment per
column. Derive column alignment from the majority of its cells, from the header
row, or not at all?

== Streaming for very large inputs

The design materializes the whole AST before writing. For a document larger
than memory this fails. Is a streaming mode — a reader emitting blocks a writer
consumes incrementally — worth the substantial complication of a two-phase
plugin contract and the loss of the filter pipeline, given the document sizes
actually encountered?

== Filter ordering and conflict

The pipeline runs stages in declaration order, which is simple and predictable.
It also means two filters that both match `div` interact in a way the user must
reason about. Is declaration order enough, or should a filter declare what it
consumes and produces so the pipeline can detect a conflict?

== Encoding detection

RTF names its code page; plain text does not. Is a heuristic detector in scope,
or does non-UTF-8 plain text require an explicit `--input-encoding`?

= Delivery Plan

#zds-figure(
  diagram(
    spacing: (19mm, 9mm),
    node-outset: 2pt,
    edge-stroke: 0.85pt + rgb("64748b"),
    box-node((0, 0), [Phase 0], [repo, build, ZDS], c-mute),
    box-node((1, 0), [Phase 1], [AST, engine, #linebreak() text → markdown], c-in),
    box-node((2, 0), [Phase 2], [markdown, csv #linebreak() readers], c-ir),
    box-node((3, 0), [Phase 3], [filters and #linebreak() the pipeline], c-aux),
    box-node((4, 0), [Phase 4], [zip, xml, docx], c-out),
    box-node((5, 0), [Phase 5+], [odt, rtf, xlsx, #linebreak() asciidoc, rst], c-out),
    edge((0, 0), (1, 0), "-|>"),
    edge((1, 0), (2, 0), edge-label[AST proven], "-|>"),
    edge((2, 0), (3, 0), edge-label[matrix proven], "-|>"),
    edge((3, 0), (4, 0), edge-label[filters proven], "-|>"),
    edge((4, 0), (5, 0), edge-label[container proven], "-|>"),
  ),
)

#tbl(
  columns: (auto, 1fr, 1fr),
  table.header([*Phase*], [*Scope*], [*Exit criterion*]),
  [0],
  [Repository skeleton, the two packages, `build.zig` with the ZDS steps, this
    record accepted.],
  [`zig build zds` produces every record; the layout is fixed.],

  [1],
  [`ast.zig`, `builder.zig`, `attr.zig`, `walk.zig`, `engine.zig`,
    `registry.zig`, `report.zig`, `limits.zig`, `text_reader.zig`,
    `markdown_writer.zig`, the CLI, the tree and golden runners.],
  [`zenfmt input.txt` emits Markdown. The validator runs on every conversion.
    Allocations per conversion are `O(log n)`, measured rather than asserted by
    inspection. Every diagnostic renders in the Elm form and has a snapshot
    test.],

  [2],
  [`markdown_reader.zig`, `csv_reader.zig`, the round-trip fixed-point suite,
    and the reader fuzz targets.],
  [Two more readers reach the one writer with no change to `engine.zig` — the
    claim the plugin architecture exists to make, tested rather than asserted.
    Markdown round-trip is a fixed point from the second pass.],

  [3],
  [`pipeline.zig` with the rebuild transform and subtree sharing, the
    `Filter.Context` API, the five built-in filters, the `examples/filters/`
    user project, and `--filters`.],
  [A user project compiles its own filter against the published module and
    produces a working binary. An identity filter is measured at one `memcpy`
    per array. Filter fuzzing runs with the validator as oracle. If a transform
    cannot be written cleanly here, the node set is wrong and this is where we
    find out.],

  [4],
  [`zip.zig`, `xml.zig`, `docx_reader.zig` with its style and numbering
    helpers, and the adversarial corpus.],
  [A real-world DOCX with headings, nested styled runs, hyperlinks, numbered
    and bulleted lists, tables with merged cells, and footnotes converts
    correctly. Every limit has a test asserting its refusal, and every refusal
    renders as a report a user can act on. Each file is under 1,000 lines.],

  [5],
  [`odt_reader.zig`, `rtf_reader.zig`, `xlsx_reader.zig`, `pptx_reader.zig`,
    and a plugin ZDS for each.],
  [The 0.1 release: every office format converts to Markdown, each with a
    record stating its mapping, its omissions, and its round-trip
    expectations.],

  [6+],
  [`asciidoc_reader.zig`, `rst_reader.zig`, `html_reader.zig`, and the
    remaining lightweight markup formats.],
  [The formats that exercise `div` and `span` as the extension mechanism,
    confirming that the node set is closed and does not need to grow per
    format.],
)

Two phases are placed deliberately. Phase 2 tests the architecture rather than
adding capability: if adding a reader requires touching `engine.zig`, that is
discovered at the cost of two small readers rather than after DOCX is written
against the wrong contract. Phase 3 puts filters before the expensive container
work for the same reason — filters are the strongest test of whether the AST is
genuinely an AST, and a transform that cannot be expressed cleanly is evidence
of a node set that needs fixing while fixing it is still cheap.

= References

- ZDS 0001, The Zen Discussion Process — lifecycle, numbering, and the
  format-record obligations this document's successors inherit.
- `Text.Pandoc.Definition` — the document model this AST is structurally
  compatible with, and the source of its node names.
- pandoc's filter documentation — the transformation model the filter system
  reproduces in Zig.
- `std.zig.Ast` — the flat, preorder, struct-of-arrays syntax tree that
  demonstrates this storage technique in the Zig compiler itself.
- CommonMark Specification, and the GFM extensions for tables, strikethrough,
  task lists, and footnotes — normative for the Markdown writer.
- ECMA-376, Office Open XML File Formats — Part 1 for WordprocessingML,
  SpreadsheetML, and PresentationML; Part 2 for the Open Packaging
  Conventions.
- OASIS Open Document Format for Office Applications v1.3.
- Microsoft Rich Text Format Specification v1.9.1.
- AsciiDoc Language Specification, and the reStructuredText Markup
  Specification.
- RFC 4180, Common Format and MIME Type for CSV Files.
- APPNOTE.TXT, the ZIP File Format Specification.
- TigerBeetle's coding style — assertions, bounded loops, no recursion, and the
  file size limit.
- Elm's compiler error messages, for the diagnostic format.
