#let zds-documents = (
  (
    number: "0001",
    slug: "zds-process",
    title: "The Zen Discussion Process",
    state: "published",
    area: "documentation",
    category: "Process Memo",
    status: "Published",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Defines the ZDS lifecycle, numbering workflow, Typst project layout, registry, and bundle export for the zenfmt monorepo.",
    source: "docs/zds/records/0001-zds-process.typ",
    html: "zds/0001-zds-process.html",
    pdf: "pdf/zds-0001-zds-process.pdf",
  ),
  (
    number: "0002",
    slug: "zenfmt-architecture",
    title: "zenfmt: Architecture and Implementation",
    state: "discussion",
    area: "architecture",
    category: "Architectural Specification",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Specifies the zenfmt document converter: a Zig-native document AST exposed as tagged-union views over flat preorder struct-of-arrays storage in one arena, a Zig filter system in the manner of build.zig with subtree sharing, comptime-validated plugin descriptors composed into bundles that keep the core free of per-format knowledge, an adjacent digest-bound JSON artifact manifest carrying provenance and plugin preservation data, OOXML ingestion and its security limits, the Markdown writer as the sole first-release output, Elm-style diagnostic reports, the TigerBeetle-derived coding standard, the CLI surface, and the phased delivery plan.",
    source: "docs/zds/records/0002-zenfmt-architecture.typ",
    html: "zds/0002-zenfmt-architecture.html",
    pdf: "pdf/zds-0002-zenfmt-architecture.pdf",
  ),
  (
    number: "0003",
    slug: "docx-reader",
    title: "The DOCX Reader",
    state: "discussion",
    area: "formats",
    category: "Format Record",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Mapping, omissions, and round-trip expectations for the DOCX reader",
    source: "docs/zds/records/0003-docx-reader.typ",
    html: "zds/0003-docx-reader.html",
    pdf: "pdf/zds-0003-docx-reader.pdf",
  ),
  (
    number: "0004",
    slug: "rtf-reader",
    title: "The RTF Reader",
    state: "discussion",
    area: "formats",
    category: "Format Record",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Mapping, omissions, and round-trip expectations for the RTF reader",
    source: "docs/zds/records/0004-rtf-reader.typ",
    html: "zds/0004-rtf-reader.html",
    pdf: "pdf/zds-0004-rtf-reader.pdf",
  ),
  (
    number: "0005",
    slug: "xlsx-reader",
    title: "The XLSX Reader",
    state: "discussion",
    area: "formats",
    category: "Format Record",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Mapping, omissions, and round-trip expectations for the XLSX reader",
    source: "docs/zds/records/0005-xlsx-reader.typ",
    html: "zds/0005-xlsx-reader.html",
    pdf: "pdf/zds-0005-xlsx-reader.pdf",
  ),
  (
    number: "0006",
    slug: "odt-reader",
    title: "The ODT Reader",
    state: "discussion",
    area: "formats",
    category: "Format Record",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Mapping, omissions, and round-trip expectations for the ODT reader",
    source: "docs/zds/records/0006-odt-reader.typ",
    html: "zds/0006-odt-reader.html",
    pdf: "pdf/zds-0006-odt-reader.pdf",
  ),
  (
    number: "0007",
    slug: "pptx-reader",
    title: "The PPTX Reader",
    state: "discussion",
    area: "formats",
    category: "Format Record",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Mapping, omissions, and round-trip expectations for the PPTX reader",
    source: "docs/zds/records/0007-pptx-reader.typ",
    html: "zds/0007-pptx-reader.html",
    pdf: "pdf/zds-0007-pptx-reader.pdf",
  ),
)
