#let zds-documents = (
  (
    number: "0001",
    slug: "zds-process",
    title: "The Zen Discussion Process",
    state: "published",
    area: "documentation",
    category: "Process Memo",
    status: "Published",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Defines the ZDS lifecycle, numbering workflow, Typst project layout, registry, and bundle export for the zenfmt monorepo.",
    source: "docs/zds/records/0001-zds-process.typ",
    html: "zds/0001-zds-process.html",
    pdf: "pdf/zds-0001-zds-process.pdf",
  ),
  (
    number: "0002",
    slug: "zenfmt-architecture",
    title: "zenfmt: Architecture and Implementation",
    state: "discussion",
    area: "architecture",
    category: "Architectural Specification",
    status: "Open for Discussion",
    created: "2026-08-06",
    updated: "2026-08-06",
    summary: "Specifies the zenfmt document converter: a pandoc-compatible document AST stored as a flat preorder struct-of-arrays in one arena, the traversal and rewriting algorithms that layout buys, a Zig filter system in the manner of build.zig with memcpy subtree sharing, a comptime plugin registry that keeps the engine free of per-format knowledge, the reader and writer contracts, OOXML ingestion and its security limits, the Markdown writer as the sole first-release output, Elm-style diagnostic reports, the TigerBeetle-derived coding standard, the CLI surface, and the phased delivery plan.",
    source: "docs/zds/records/0002-zenfmt-architecture.typ",
    html: "zds/0002-zenfmt-architecture.html",
    pdf: "pdf/zds-0002-zenfmt-architecture.pdf",
  ),
)
